apiVersion: v1
kind: Service
metadata:
  name: player-ingress-backend-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: player-app
    run: player-ingress-backend-service
  type: NodePort