apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: player-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: player-global-ip
  labels:
    app: player
spec:
  defaultBackend:
    service:
      name: player-app-service
      port:
        number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: player-app-service
  labels:
    app: player
spec:
  type: NodePort
  selector:
    app: player
  ports:
  - port: 80
    targetPort: 8080